version: '3'

services:
  db:
    image: postgres:latest
    container_name: project_manager_db
    environment:
      POSTGRES_DB: project_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"